package com.thingtrack.bustrack.view.module.invoice.addon;

import java.io.Serializable;

import org.vaadin.peter.buttongroup.ButtonGroup;

import com.thingtrack.konekti.domain.Invoice;
import com.thingtrack.konekti.view.addon.data.BindingSource;
import com.thingtrack.konekti.view.addon.data.BindingSource.IndexChangeEvent;
import com.thingtrack.konekti.view.addon.data.BindingSource.IndexChangeListener;
import com.thingtrack.konekti.view.addon.ui.AbstractToolbar;
import com.thingtrack.konekti.view.kernel.ui.layout.IViewContainer;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.terminal.gwt.client.MouseEventDetails;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Component;
import com.vaadin.ui.ComponentContainer;
import com.vaadin.ui.HorizontalLayout;

@SuppressWarnings("serial")
public class InvoiceToolbar extends AbstractToolbar {
	@AutoGenerated
	private HorizontalLayout toolbarLayout;

	@AutoGenerated
	private Button btnBill;

	@AutoGenerated
	private Button btnClose;
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private Object register;
	
	private int position = 0;
		
	// navigator button listeners
	private ClickBillButtonListener listenerBillButton = null;
	private ClickCloseButtonListener listenerCloseButton = null;
	
	private IViewContainer viewContainer;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */	
	public InvoiceToolbar(int position, final BindingSource<?> bindingSource, IViewContainer viewContainer) {
		super(position, bindingSource);
			
		buildMainLayout();
		//setCompositionRoot(mainLayout);

		// TODO add user code here
		this.position = position;
		this.viewContainer = viewContainer;
		
		setBindingSource(bindingSource);
		
		btnBill.setDescription("Rechazo Oferta");
		
		// set tool button listener
		btnBill.addListener(new ClickListener() {			
			public void buttonClick(ClickEvent event) {
				int index = bindingSource.getIndex();
				
				if (index == 0)
					return;
				
				register = bindingSource.getItemId();
				
				if (listenerBillButton != null)
					listenerBillButton.billButtonClick(new ClickNavigationEvent(event.getButton(), event.getComponent() , null, register, 0));					
				
			}
		});
		
		btnClose.addListener(new ClickListener() {			
			public void buttonClick(ClickEvent event) {
				int index = bindingSource.getIndex();
				
				if (index == 0)
					return;
				
				register = bindingSource.getItemId();
				
				if (listenerCloseButton != null)
					listenerCloseButton.closeButtonClick(new ClickNavigationEvent(event.getButton(), event.getComponent() , null, register, 0));					
				
			}
		});
	}
	
	@Override
	public int getPosition() {
		return this.position;
		
	}

	@Override
	public ComponentContainer getContent() {
		return this.toolbarLayout;
		
	}
	
	public void addListenerBillButton(ClickBillButtonListener listener) {
		this.listenerBillButton = listener;
		
	}
	
	public void addListenerCloseButton(ClickCloseButtonListener listener) {
		this.listenerCloseButton = listener;
		
	}
	
	public interface ClickBillButtonListener extends Serializable {
        public void billButtonClick(ClickNavigationEvent event);

    }
	
	public interface ClickCloseButtonListener extends Serializable {
        public void closeButtonClick(ClickNavigationEvent event);

    }
	
	public class ClickNavigationEvent extends ClickEvent {
		private int index;
		private Object register;
		
		public ClickNavigationEvent(Button button, Component source) {
			button.super(source);
			
		}

		public ClickNavigationEvent(Button button, Component source, MouseEventDetails details) {
			button.super(source, details);
			
		}

		public ClickNavigationEvent(Button button, Component source, MouseEventDetails details, Object register, int index) {
			button.super(source, details);
			
			this.index = index;
			this.register = register;
		}

		public int getIndex() {
			return this.index;
			
		}
		
		public Object getRegister() {
			return this.register;
			
		}
		
	  }
	
	@Override
	public void setBindingSource(BindingSource<?> bindingSource) {
		this.bindingSource = bindingSource;
		
		// add change index binding source
		if (bindingSource != null) {
			bindingSource.addListenerToolBar((IndexChangeListener)this);
			
		}
		
	}
	
	@Override
	public void bindingSourceIndexChange(IndexChangeEvent event) {
		if (bindingSource != null) {
			Invoice invoiceSelected = (Invoice)event.getRegister();
			
			if (invoiceSelected == null)
				return;
						
			if (invoiceSelected.getInvoiceStatus().getCode().equals(Invoice.STATUS.OPENED.name())) {
				btnBill.setEnabled(true);
				btnClose.setEnabled(false);
			}
			else if (invoiceSelected.getInvoiceStatus().getCode().equals(Invoice.STATUS.SENT.name())) { 
				btnBill.setEnabled(false);
				btnClose.setEnabled(true);
			}
			else if (invoiceSelected.getInvoiceStatus().getCode().equals(Invoice.STATUS.CLOSED.name())) {
				btnBill.setEnabled(false);
				btnClose.setEnabled(false);
			}			
			else {
				btnBill.setEnabled(false);
				btnClose.setEnabled(false);
			}
		}
		
	}
	
	@AutoGenerated
	private void buildMainLayout() {
		toolbarLayout = buildToolbarLayout();
		addComponent(toolbarLayout);
		
	}
	
	@AutoGenerated
	private HorizontalLayout buildToolbarLayout() {		
		toolbarLayout = new HorizontalLayout();
		toolbarLayout.setImmediate(false);
		toolbarLayout.setSpacing(true);
		
		ButtonGroup invoiceButtonGroup = new ButtonGroup();
		toolbarLayout.addComponent(invoiceButtonGroup);
		
		// btnBill
		btnBill = new Button();
		btnBill.setCaption("Enviar");
		btnBill.setWidth("-1px");
		btnBill.setHeight("-1px");
		btnBill.setIcon(new ThemeResource("../konekti/images/icons/offerrequest-toolbar/paper-bag--exclamation.png"));
		
		invoiceButtonGroup.addButton(btnBill);
		
		// btnClose
		btnClose = new Button();
		btnClose.setCaption("Cerrar");
		btnClose.setWidth("-1px");
		btnClose.setHeight("-1px");
		btnClose.setIcon(new ThemeResource("../konekti/images/icons/offerrequest-toolbar/paper-bag--arrow.png"));
		
		invoiceButtonGroup.addButton(btnClose);
		
		return toolbarLayout;
	}

}
