package com.thingtrack.bustrack.view.module.offer.internal;

import java.text.SimpleDateFormat;
import java.util.Date;

import org.vaadin.dialogs.ConfirmDialog;

import com.thingtrack.bustrack.view.module.offer.addon.OfferToolbar;
import com.thingtrack.bustrack.view.module.offer.addon.OfferToolbar.ClickRejectButtonListener;
import com.thingtrack.konekti.domain.Offer;
import com.thingtrack.konekti.service.api.OfferService;
import com.thingtrack.konekti.view.addon.data.BindingSource;
import com.thingtrack.konekti.view.addon.ui.AbstractView;
import com.thingtrack.konekti.view.addon.ui.BoxToolbar;
import com.thingtrack.konekti.view.addon.ui.BoxToolbar.ClickFilterButtonListener;
import com.thingtrack.konekti.view.addon.ui.BoxToolbar.ClickPrintButtonListener;
import com.thingtrack.konekti.view.addon.ui.DataGridView;
import com.thingtrack.konekti.view.addon.ui.EditionToolbar;
import com.thingtrack.konekti.view.addon.ui.EditionToolbar.ClickNavigationEvent;
import com.thingtrack.konekti.view.addon.ui.NavigationToolbar;
import com.thingtrack.konekti.view.addon.ui.EditionToolbar.ClickAddButtonListener;
import com.thingtrack.konekti.view.addon.ui.EditionToolbar.ClickEditButtonListener;
import com.thingtrack.konekti.view.addon.ui.EditionToolbar.ClickRemoveButtonListener;
import com.thingtrack.konekti.view.addon.ui.NavigationToolbar.ClickDownButtonListener;
import com.thingtrack.konekti.view.addon.ui.NavigationToolbar.ClickRefreshButtonListener;
import com.thingtrack.konekti.view.addon.ui.WindowDialog;
import com.thingtrack.konekti.view.addon.ui.WindowDialog.DialogResult;
import com.thingtrack.konekti.view.kernel.IWorkbenchContext;
import com.thingtrack.konekti.view.kernel.ui.layout.IViewContainer;
import com.thingtrack.konekti.view.web.form.OfferViewForm;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class OfferView extends AbstractView 
	implements ClickDownButtonListener, ClickRefreshButtonListener, ClickAddButtonListener, 
			   ClickEditButtonListener, ClickRemoveButtonListener, ClickRejectButtonListener, ClickFilterButtonListener,
			   ClickPrintButtonListener{
			
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private DataGridView dgOffer;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private IWorkbenchContext context;
	private OfferService offerService;
	
	private BindingSource<Offer> bsOffer =  new BindingSource<Offer>(Offer.class, 0);
	
	private NavigationToolbar navigationToolbar;
	private EditionToolbar editionToolbar;
	private BoxToolbar boxToolbar;
	private OfferToolbar offerToolbar;
		
	private IViewContainer viewContainer;
		
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public OfferView(IViewContainer viewContainer) {		
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here	
		// set Slide View Services and ViewContainer to navigate
		this.viewContainer = viewContainer;
		this.offerService = OfferViewContainer.getOfferService();
		this.context = OfferViewContainer.getContext();
		
		// initialize datasource views		
		initView();	
	}

	private void initView() {
		// initialize Slide View Organization View
		dgOffer.setImmediate(true);		
		
		refreshBindindSource();
		
		// STEP 01: create grid view for slide Organization View
		try {
			dgOffer.setBindingSource(bsOffer);
			dgOffer.setVisibleColumns(new String[] { "organization.name", "code", "offerType.description", "offerClient.name", "observation", "offerStatus.description", "offerDate" } );       
			dgOffer.setColumnHeaders(new String[] { "Organización", "Código", "Tipo", "Cliente", "Observaciones", "Estado", "Fecha" } );
			
			dgOffer.setColumnCollapsed("organization.name", true);
		}
		catch(Exception ex) {
			ex.getMessage();
		}
			
		// STEP 02: create toolbar for slide Employee Agent View
		navigationToolbar = new NavigationToolbar(0, bsOffer, viewContainer);
		editionToolbar = new EditionToolbar(1, bsOffer);
		boxToolbar = new BoxToolbar(2, bsOffer);
		offerToolbar = new OfferToolbar(3, bsOffer, viewContainer);
		
		navigationToolbar.addListenerDownButton(this);
		navigationToolbar.addListenerRefreshButton(this);
		
		editionToolbar.addListenerAddButton(this);
		editionToolbar.addListenerEditButton(this);
		editionToolbar.addListenerDeleteButton(this);
		
		boxToolbar.addListenerFilterButton(this);
		boxToolbar.addListenerPrintButton(this);
				
		offerToolbar.addListenerRejectButton(this);
		
		dgOffer.addListenerAddButton(this);
		dgOffer.addListenerEditButton(this);
		dgOffer.addListenerDeleteButton(this);
		
		removeAllToolbar();
		
		addToolbar(navigationToolbar);
		addToolbar(boxToolbar);
		addToolbar(editionToolbar);
		addToolbar(offerToolbar);

	}
	
	private void refreshBindindSource() {
		try {		
			bsOffer.removeAllItems();
			bsOffer.addAll(offerService.getAll());	
			
			bsOffer.addNestedContainerProperty("organization.name");
			bsOffer.addNestedContainerProperty("offerClient.name");
			bsOffer.addNestedContainerProperty("offerType.description");
			bsOffer.addNestedContainerProperty("offerStatus.description");
		} catch (IllegalArgumentException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}		
	}
	
	@Override
	public void downButtonClick(NavigationToolbar.ClickNavigationEvent event) {
		Offer offerSelected  = null;
		
		if (bsOffer.getItemIds().size() > 0) {
			// get selected Organization
			offerSelected = (Offer)bsOffer.getItemId();
			
			// inject the locations data from organization in the detail Location View
			OfferLineView offerLineView = (OfferLineView)viewContainer.getNext();
			offerLineView.setOffer(offerSelected);
			
			// roll to the detail Location View
			viewContainer.getSliderView().rollNext();
		}
		
	}
	
	@Override
	public void refreshButtonClick(NavigationToolbar.ClickNavigationEvent event) {
		refreshBindindSource();
		
	}

	private void refreshDataGridView(Offer savedOffer) {
		if(bsOffer.containsId(savedOffer)){			
			Offer previousOffer = bsOffer.prevItemId(savedOffer);
			
			bsOffer.removeItem(savedOffer);
			bsOffer.addItemAfter(previousOffer, savedOffer);
			bsOffer.setItemId(savedOffer);
		}
		else
			bsOffer.addItem(savedOffer);
		
	}
	
	@Override
	public void addButtonClick(ClickNavigationEvent event) {
		Offer offer = null;
		try {
			offer = offerService.createNewOffer(context.getOrganization());
		} catch (Exception e) {
			throw new RuntimeException(
					"¡No se pudo crear el nuevo código oferta!",
					e);
		}	
		
		try {
			@SuppressWarnings("unused")
			WindowDialog<Offer> windowDialog = new WindowDialog<Offer>(getWindow(), "Nueva Oferta", 
					"Guardar", DialogResult.SAVE, "Cancelar", DialogResult.CANCEL, 
					new OfferViewForm(), offer, 
					new WindowDialog.CloseWindowDialogListener<Offer>() {
			    public void windowDialogClose(WindowDialog<Offer>.CloseWindowDialogEvent<Offer> event) {
			    	if (event.getDialogResult() != WindowDialog.DialogResult.SAVE)
			    		return ;
			    	
			    	try {
			    		Offer savingOffer = event.getDomainEntity();
			    		
			    		Offer savedOffer = offerService.save(savingOffer);
			    		
			    		refreshDataGridView(savedOffer);
			    		
					} catch (Exception e) {
						throw new RuntimeException(
								"¡No se pudo crear la nueva oferta!",
								e);
						
					}
			    }

			});
		} catch (IllegalArgumentException e) {
			throw new RuntimeException(
					"¡No se pudo abrir el formulario Nueva Oferta!", e);
		} catch (Exception e) {
			throw new RuntimeException(
					"¡No se pudo abrir el formulario Nueva Oferta!", e);
		} 
		
	}
	
	@Override
	public void editButtonClick(ClickNavigationEvent event) {
		Offer editingOffer = (Offer) event.getRegister();

		try {
			@SuppressWarnings("unused")
			WindowDialog<Offer> windowDialog = new WindowDialog<Offer>(getWindow(), "Editor Oferta", 
					"Guardar", DialogResult.SAVE, "Cancelar", DialogResult.CANCEL, 
					new OfferViewForm(), editingOffer, 
					new WindowDialog.CloseWindowDialogListener<Offer>() {
			    public void windowDialogClose(WindowDialog<Offer>.CloseWindowDialogEvent<Offer> event) {
			    	if (event.getDialogResult() != WindowDialog.DialogResult.SAVE)
			    		return ;
			    	
			    	try {
			    		Offer savingOffer = event.getDomainEntity();
			    		
			    		Offer savedOfferRequest = offerService.save(savingOffer);
			    		
			    		refreshDataGridView(savedOfferRequest);
			    		
					} catch (Exception e) {
						throw new RuntimeException(
								"¡No se pudo modificar la oferta!", e);
						
					}
			    }

			});
		} catch (IllegalArgumentException e) {
			throw new RuntimeException(
					"¡No se pudo abrir el formulario Editor Oferta!", e);
		} catch (Exception e) {
			throw new RuntimeException(
					"¡No se pudo abrir el formulario Editor Oferta!", e);
		} 
		
	}
	
	@Override
	public void deleteButtonClick(ClickNavigationEvent event) {
		final Offer editingOffer = (Offer) event.getRegister();
		
		if (editingOffer == null)
			return;
		
		ConfirmDialog.show(getWindow(), "Borrar Oferta",
		        "¿Estás seguro?", "Si", "No",
		        new ConfirmDialog.Listener() {

		            public void onClose(ConfirmDialog dialog) {
		                if (dialog.isConfirmed()) {
		            		try {
		            			offerService.delete(editingOffer);
		            			
		            			// refresh
		            			refreshBindindSource();
		            			
		            		} catch (IllegalArgumentException e) {
								throw new RuntimeException(
										"¡No se pudo borrar la oferta!", e);
		            		} catch (Exception e) {
								throw new RuntimeException(
										"¡No se pudo borrar la oferta!", e);
		            		}
		                } 
		            }
		        });
		
	}
	
	@Override
	public void rejectButtonClick(OfferToolbar.ClickNavigationEvent event) {
		Offer editingOffer = (Offer) event.getRegister();
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// dgEmployee
		dgOffer = new DataGridView() {
		    @Override
		    protected String formatPropertyValue(Object rowId,
		            Object colId, Property property) {
		    	// Format by property type
		        if (property.getType() == Date.class) {
		            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
		            
		            return df.format((Date)property.getValue());
		        }

		        return super.formatPropertyValue(rowId, colId, property);
		    }
		};
		
		dgOffer.setImmediate(false);
		dgOffer.setWidth("100.0%");
		dgOffer.setHeight("100.0%");
		mainLayout.addComponent(dgOffer);
		mainLayout.setExpandRatio(dgOffer, 1.0f);
		
		return mainLayout;
	}

	@Override
	public void filterButtonClick(BoxToolbar.ClickNavigationEvent event) {		
		dgOffer.setFilterBarVisible();
		
	}

	@Override
	public void printButtonClick(BoxToolbar.ClickNavigationEvent event) {
		try {
			dgOffer.print("Listado Ofertas");
		}
		catch (Exception e) {
			throw new RuntimeException("¡No se pudo imprimir el informe!", e);
		}
		
	}
	
}
