package com.thingtrack.bustrack.view.module.servicedesigner.internal.ui;

import com.thingtrack.konekti.domain.Service;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class OfferRequestLineViewForm extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private TextField passengersTextField;
	@AutoGenerated
	private TextField clientTextField;
	@AutoGenerated
	private TextArea commentsTextArea;
	@AutoGenerated
	private TextArea intermediateStopsTextArea;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private TextField endDateTextField;	
	@AutoGenerated
	private TextField endStopTextField;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private TextField startDateTextField;
	@AutoGenerated
	private TextField startStopTextField;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private TextField offerlineNumbertextField;
	@AutoGenerated
	private TextField offerCodeTextField;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public OfferRequestLineViewForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("500px");
		mainLayout.setHeight("450px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("500px");
		setHeight("450px");
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout.addComponent(horizontalLayout_4);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		
		// intermediateStopsTextArea
		intermediateStopsTextArea = new TextArea();
		intermediateStopsTextArea.setCaption("Paradas");
		intermediateStopsTextArea.setImmediate(false);
		intermediateStopsTextArea.setWidth("100.0%");
		intermediateStopsTextArea.setHeight("-1px");
		mainLayout.addComponent(intermediateStopsTextArea);
		
		// commentsTextArea
		commentsTextArea = new TextArea();
		commentsTextArea.setCaption("Comentarios");
		commentsTextArea.setImmediate(false);
		commentsTextArea.setWidth("100.0%");
		commentsTextArea.setHeight("-1px");
		mainLayout.addComponent(commentsTextArea);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		mainLayout.setExpandRatio(horizontalLayout_3, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("100.0%");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		horizontalLayout_4.setSpacing(true);
		
		// OfferCodeTextField
		offerCodeTextField = new TextField();
		offerCodeTextField.setCaption("Código de oferta");
		offerCodeTextField.setImmediate(false);
		offerCodeTextField.setWidth("100.0%");
		offerCodeTextField.setHeight("-1px");
		horizontalLayout_4.addComponent(offerCodeTextField);
		horizontalLayout_4.setExpandRatio(offerCodeTextField, 1.0f);
		
		// offerlineNumbertextField
		offerlineNumbertextField = new TextField();
		offerlineNumbertextField.setCaption("Número de línea de oferta");
		offerlineNumbertextField.setImmediate(false);
		offerlineNumbertextField.setWidth("100.0%");
		offerlineNumbertextField.setHeight("-1px");
		horizontalLayout_4.addComponent(offerlineNumbertextField);
		horizontalLayout_4.setExpandRatio(offerlineNumbertextField, 1.0f);
		
		return horizontalLayout_4;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// startStopTextField
		startStopTextField = new TextField();
		startStopTextField.setCaption("Origen");
		startStopTextField.setImmediate(false);
		startStopTextField.setWidth("100.0%");
		startStopTextField.setHeight("-1px");
		horizontalLayout_1.addComponent(startStopTextField);
		horizontalLayout_1.setExpandRatio(startStopTextField, 1.0f);
		
		// startDateTextField
		startDateTextField = new TextField();
		startDateTextField.setCaption("Fecha origen");
		startDateTextField.setImmediate(false);
		startDateTextField.setWidth("100.0%");
		startDateTextField.setHeight("-1px");
		horizontalLayout_1.addComponent(startDateTextField);
		horizontalLayout_1.setExpandRatio(startDateTextField, 1.0f);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// endStopTextField
		endStopTextField = new TextField();
		endStopTextField.setCaption("Destino");
		endStopTextField.setImmediate(false);
		endStopTextField.setWidth("100.0%");
		endStopTextField.setHeight("-1px");
		horizontalLayout_2.addComponent(endStopTextField);
		horizontalLayout_2.setExpandRatio(endStopTextField, 1.0f);
		
		// endDateTextField
		endDateTextField = new TextField();
		endDateTextField.setCaption("Fecha destino");
		endDateTextField.setImmediate(false);
		endDateTextField.setWidth("100.0%");
		endDateTextField.setHeight("-1px");
		horizontalLayout_2.addComponent(endDateTextField);
		horizontalLayout_2.setExpandRatio(endDateTextField, 1.0f);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("100.0%");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		horizontalLayout_3.setSpacing(true);
		
		// clientTextField
		clientTextField = new TextField();
		clientTextField.setCaption("Cliente");
		clientTextField.setImmediate(false);
		clientTextField.setWidth("100.0%");
		clientTextField.setHeight("-1px");
		horizontalLayout_3.addComponent(clientTextField);
		horizontalLayout_3.setExpandRatio(clientTextField, 1.0f);
		
		// passengersTextField
		passengersTextField = new TextField();
		passengersTextField.setCaption("Pasajeros");
		passengersTextField.setImmediate(false);
		passengersTextField.setWidth("100px");
		passengersTextField.setHeight("-1px");
		horizontalLayout_3.addComponent(passengersTextField);
		
		return horizontalLayout_3;
	}
	
	public void setService(Service service) {		
		if (service.getOfferLine() != null) {
			offerCodeTextField.setValue(service.getOfferLine().getOffer().getCode());
			offerlineNumbertextField.setValue(service.getOfferLine().getNumber());
	//		startStopTextField.setValue(service.getOfferLine().getOffer().getOfferRequest().
		}
	}

}
